version: '3.8'

services:
  frontend-admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: shop_frontend-admin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:3002:3000"
    networks:
      - shop-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shop-network:
    external: true
